import { NextResponse } from 'next/server';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { put } from '@vercel/blob';
import { z } from 'zod';
import { db } from '@/lib/db';
import { createPlayerSession } from '@/lib/auth';

const schema=z.object({playerName:z.string().trim().min(2).max(80),minecraftUsername:z.string().regex(/^[A-Za-z0-9_]{3,16}$/),discordUsername:z.string().trim().min(2).max(80),discordId:z.string().regex(/^\d{17,20}$/),serverMode:z.string().trim().min(2).max(30),playerBio:z.string().trim().min(10).max(600)});
const signatures={'image/jpeg':'ffd8ff','image/png':'89504e47','image/webp':'52494646'};
export async function POST(request:Request){try{const form=await request.formData();const values=Object.fromEntries([...form.entries()].filter(([,v])=>typeof v==='string'));const parsed=schema.safeParse(values);if(!parsed.success)return NextResponse.json({error:'Please check the highlighted application details.'},{status:400});const photo=form.get('photo');if(!(photo instanceof File)||photo.size>5*1024*1024)return NextResponse.json({error:'A photo under 5MB is required.'},{status:400});const bytes=new Uint8Array(await photo.arrayBuffer());const signature=Buffer.from(bytes.slice(0,4)).toString('hex').toLowerCase();if(!Object.values(signatures).some(s=>signature.startsWith(s)))return NextResponse.json({error:'Unsupported or invalid image file.'},{status:400});const count=await db.application.count();const applicationId=`YUG-APP-${String(count+1).padStart(6,'0')}`;const credential=crypto.randomBytes(12).toString('hex');const key=`applications/${crypto.randomUUID()}.${photo.type.split('/')[1]}`;const blob=await put(key,Buffer.from(bytes),{access:'public',contentType:photo.type,addRandomSuffix:false});const application=await db.application.create({data:{...parsed.data,applicationId,photoKey:blob.url,accessHash:await bcrypt.hash(credential,12),history:{create:{action:'Application submitted.',actor:'PLAYER',newStatus:'PENDING'}}}});await createPlayerSession(application.id);return NextResponse.json({id:applicationId,credential});}catch(error){console.error(error);return NextResponse.json({error:'The application could not be saved.'},{status:500})}}
